### ISSUE TITLE
Implement a mechanism for COEBS

### ISSUE THREAD

**Issue by dbruns** [princeton-nlp/tree-of-thought-llm#25]
https://github.com/dbruns/COEBS-Protocol/blob/main/protocol_specs.txt

This is the start of a repo to define the specs for COEBS. I'm not ready to share the most concise and incredibly effective prompts that I've come up with yet because I need to do a little more testing, but I believe any use of AI should involve some form of COEBS so that the results can be reconciled with the personal code of ethics and belief system of the user or organization using the ToT. 

I believe this concept is a fundamental requirement for the safe use of AI. I'd be happy to find time in the near future to make a pull request, but I'd like to see what at least 1 other person can come up with that works before I submit one.

**Comment by dbruns** [comment]
For example, having some sort of ENV var or text file with a defined set of COEBS that is condensed into the beginning of a single prompt and can be used for reference. This becomes more and more relevant the further the ToT use-case goes from math-related topics.

**Comment by ysymyth** [comment]
since it's not a code issue I'll close for now. feel free to pull request or open a new one if needed
