### ISSUE TITLE
Feature request: pyproject.toml & pypi package

### ISSUE THREAD

**Issue by elliottower** [princeton-nlp/tree-of-thought-llm#27]
The other repository has a pypi release but it doesn't even run nor does the regular install without editing some files, would imagine it would be a pretty important feature to allow people to use this repo more easily via `pip install` (though it'd have to be tree-of-thought-llm as the other repo took the name tree-of-thought). Would be happy to help out with this, just making an issue to see if the maintainers are already working on it or what the status of things is.

**Comment by ysymyth** [comment]
hi @elliottower thanks! we are in the process of reclaiming the `tree-of-thoughts` pip package: https://github.com/pypi/support/issues/2928

**Comment by ysymyth** [comment]
Hi @elliottower please check out https://github.com/princeton-nlp/tree-of-thought-llm/tree/pypi

Feel free to test run and let me know if there's any issues. I plan to merge it into master, and have a `tot` pip package by this week.
