### ISSUE TITLE
Does sample selection require np.random.choice(replace=False)?

### ISSUE THREAD

**Issue by KevinH48264** [princeton-nlp/tree-of-thought-llm#31]
In the following selection code in run.py, do you need to add replace=False? Otherwise if args.n_select_sample = 2, you might still get the same id to select twice, which you don't want (ie. keep choice 1 and choice 1, instead of keep 2 different choices)

Current version:
```
# selection
        if args.method_select == 'sample':
            ps = np.array(values) / sum(values)
            select_ids = np.random.choice(ids, size=args.n_select_sample, p=ps).tolist()
```

Proposed version:
```
# selection
        if args.method_select == 'sample':
            ps = np.array(values) / sum(values)
            select_ids = np.random.choice(ids, size=args.n_select_sample, p=ps, replace=False).tolist()
```

Also, thank you for the great work you and your team have done here

**Comment by ysymyth** [comment]
hi @KevinH48264 , good detail to notice! in our paper experiments, ``args.method_select`` is always ``greedy`` not ``sample``. 

as for ``sample``, I feel without replacement might lead to including low-value samples when generated samples are not many, e.g. when beam size is 5 and sample size is 5, without replacement every sample must be included even though some are impossible. instead, with replacement only high-value ones are chosen, and they are immediately de-duplicated in the next sample phase. feel free to try some experiments and let me know!
