### ISSUE TITLE
How to use it on oobabooga / text-generation-webui?

### ISSUE THREAD

**Issue by xcaliber123** [princeton-nlp/tree-of-thought-llm#34]
Is there any way you to use it with oobabooga's text-generation-webui? Other AI programs are just too slow on AMD APU based PC.

**Comment by ysymyth** [comment]
Shouldn't be hard just to add new LLMs to `model.py`. Happy to pull request.

But note that even GPT-3.5 performance on ToT is a lot worse than GPT-4, let alone smaller open source LLMs. For example, see discussion in https://github.com/princeton-nlp/tree-of-thought-llm/issues/24
