### ISSUE TITLE
src/tot directory issue

### ISSUE THREAD

**Issue by rkuo2000** [princeton-nlp/tree-of-thought-llm#38]
since you put code under src/tot,
most of your codes are ‵from tot.methods.bfs import solve
when running those codes, it will show error of not finding tot

I move src/tot to tot, then problem solved !
revised in https://github.com/rkuo2000/tree-of-thought-llm

**Comment by ysymyth** [comment]
hi, you need to `pip install tree-of-thoughts-llm` before `import tot` --- check README.md
