### ISSUE TITLE
MiniCrosswordsTask() troubles

### ISSUE THREAD

**Issue by eobrie17** [princeton-nlp/tree-of-thought-llm#40]
Do you think you could provide an example of the code you have that runs the MiniCrosswordsTask()? I think I am doing something wrong as every time I run it I get the errors: "AttributeError: 'MiniCrosswordsTask' object has no attribute 'value_prompt_wrap'". Thank you so much-- I really appreciate it!

**Comment by ysymyth** [comment]
hi, check https://github.com/princeton-nlp/tree-of-thought-llm/blob/master/scripts/crosswords/search_crosswords-dfs.ipynb ?

**Comment by ysymyth** [comment]
close for now, feel free to open a new one
