### ISSUE TITLE
The first step of Setup(Setup OpenAI key) is not right in Google Colab ubuntu environment

### ISSUE THREAD

**Issue by WingsReal** [princeton-nlp/tree-of-thought-llm#41]
"Set up OpenAI API key and store in environment variable OPENAI_API_KEY (see [here](https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety))".

Following the instructions given by the link does not successfully set up the OpenAI API key.

Please update 

echo "export OPENAI_API_KEY='yourkey'" >> ~/.zshrc

to

import os
os.environ['MY_VARIABLE'] = 'my_value'

**Comment by WingsReal** [comment]
please use option 2 in Google Colab ubuntu environment

**Comment by HU-xiaobai** [comment]
@WingsReal hello where do you add the command"import os
os.environ['MY_VARIABLE'] = 'my_value'"? I try to add them in the colan notebook or at the beginning of python document, it is not working. how do you add the openai API key to the environment variable in colab?

**Comment by HU-xiaobai** [comment]
sorry it is fixed..

**Comment by HU-xiaobai** [comment]
little wired, suddenly fixed
