### ISSUE TITLE
Text generation task is not implemented as what the paper shows

### ISSUE THREAD

**Issue by danielwonght** [princeton-nlp/tree-of-thought-llm#45]
It seems that the text generation does not follow the instruction shown in the paper. The paper mentions 

> We build a ToT with depth 2 (and only 1 intermediate thought step) — the LM first generates k = 5 plans and votes for the best one

But I can not find the code for only generating plans and valuing the generated plans. What the code implemented is only building a ToT with depth 1, meaning that the passage is generated in one step. 

I am wondering whether the finding above is true or not?

**Comment by ysymyth** [comment]
https://github.com/princeton-nlp/tree-of-thought-llm/blob/f10dd7a586268ea0d996308bb7126420bbe8d247/src/tot/tasks/text.py#L23

As shown here, it has two steps: generate 5 plans then vote for the best one. Then, based on the best plan, generate 5 passages then vote for the best one.
