### ISSUE TITLE
MiniCrosswords performance

### ISSUE THREAD

**Issue by mhd0528** [princeton-nlp/tree-of-thought-llm#46]
Hi, 

I have tried to reproduce the result on Crosswords with the given notebook. But the performance I got with GPT-4 is much lower than what is provided in the log. May I ask if you have tried to run it multiple times after the update of GPT-4? My assumption is that there might be some changes on GPT-4 end. Or, since there are multiple version of GPT-4 API provide by OpenAI, may I ask which one you were using?

Thanks in advance

**Comment by ysymyth** [comment]
Interesting. Can you share your command and results?

**Comment by mhd0528** [comment]
Yes, 

I ran the cells in the ipynb file in the crosswords folder. 

https://github.com/princeton-nlp/tree-of-thought-llm/blob/7d1bd7eb4dd656b325f6c70f2f9b1ded9a8368bf/scripts/crosswords/search_crosswords-dfs.ipynb

The result is attached below. We ran on the first 12 examples (0, 5, ...55) in the test set. Only #8 has results with r_word = 1.0 or r_game = true
[tot-0.7-infoss_dfs_prune.txt](https://github.com/princeton-nlp/tree-of-thought-llm/files/12379565/tot-0.7-infoss_dfs_prune.txt)

Thanks

**Comment by ysymyth** [comment]
Interesting, from the file you provided, it does seem that GPT-4 became weaker. For example, in the second test case, previously the first three moves were
```
            "actions": [
                "h4. seder",
                "v3. evade",
                "v1. arise"
            ],
```
but now it is 
```
            "actions": [
                "h4. seder",
                "v3. evade",
                "v4. seder"
            ],
```

I would be happy to run again some time, and feel free to do some analysis. But unfortunately we cannot control GPT-4 or guarantee exact reproducibility of experiments run on GPT-4.

**Comment by mhd0528** [comment]
I agree. It's hard to exactly reproduce the result with GPT-4. I also notice that the experiments are finished in May. In this case, do you think it is worth running it with GPT4-0314 or other earlier versions would help on this issue?

**Comment by ysymyth** [comment]
probably. if you can run and share it'd be awesome!
