### ISSUE TITLE
how to get the value

### ISSUE THREAD

**Issue by junjiexiao1** [princeton-nlp/tree-of-thought-llm#49]
In game24, give us four numbers, for example "4 5 6 10", the possible follow-up steps are: "4 + 5 = 9 (left: 6 9 10)\n",
               "5 + 6 = 11 (left: 4 10 11)\n",
               "6 + 10 = 16 (left: 4 5 16)\n",
               "4 * 5 = 20 (left: 6 10 20)\n",
               "5 * 6 = 30 (left: 4 10 30)\n",
               "6 * 10 = 60 (left: 4 5 60)\n",
               "4 - 5 = -1 (left: -1 6 10)\n",
               "5 - 6 = -1 (left: 4 -1 10)\n",
               "10 - 6 = 4 (left: 4 4 5)\n",
               "10 - 4 = 6 (left: 5 6 6)\n",
               "10 / 5 = 2 (left: 2 4 6)\n",
               "6 / 4 = 1.5 (left: 1.5 5 10)\n"
Next, the value of these subsequent steps is obtained. I want to know how to calculate it.

**Comment by ysymyth** [comment]
https://github.com/princeton-nlp/tree-of-thought-llm/blob/7d1bd7eb4dd656b325f6c70f2f9b1ded9a8368bf/src/tot/methods/bfs.py#L16
