### ISSUE TITLE
A Missing Default Argument in MiniCrosswordsTask

### ISSUE THREAD

**Issue by cjxhwyt** [princeton-nlp/tree-of-thought-llm#51]
Hi, when I run [scripts/crosswords/cot_sampling.sh](https://github.com/princeton-nlp/tree-of-thought-llm/blob/master/scripts/crosswords/cot_sampling.sh#L6) (same for the standard one), there is an error message:

> Traceback (most recent call last):
  File "... tree-of-thought-llm/run.py", line 69, in <module>
    run(args)
  File "... tree-of-thought-llm/run.py", line 10, in run
    task = get_task(args.task)
           ^^^^^^^^^^^^^^^^^^^
  File "... tree-of-thought-llm/src/tot/tasks/__init__.py", line 10, in get_task
    return MiniCrosswordsTask()
           ^^^^^^^^^^^^^^^^^^^^
TypeError: MiniCrosswordsTask.__init__() missing 1 required positional argument: 'file'

I'm wondering whether this issue might be caused by the missingness of the default ``file`` argument in Line 162 of [src/tot/tasks/crosswords.py](https://github.com/princeton-nlp/tree-of-thought-llm/blob/master/src/tot/tasks/crosswords.py#L162) - as in Line 10 of [src/tot/tasks/__init__.py](https://github.com/princeton-nlp/tree-of-thought-llm/blob/master/src/tot/tasks/__init__.py#L10), it calls ``MiniCrosswordsTask()`` without any argument.

Many thanks!

**Comment by ysymyth** [comment]
hi, thanks for the pointer! I've updated crosswords.py, should work now!
