### ISSUE TITLE
Inquiry on the Game 24 result of Tree-of-Thought 

### ISSUE THREAD

**Issue by jin8** [princeton-nlp/tree-of-thought-llm#53]
I have recomputed the success rate for ToT, using the provided JSON file `logs/game24/gpt-4_0.7_propose1_value3_greedy5_start900_end1000.json` .

Based on the provided JSON file, the recomputed success rates of ToT (b=5) are as follows:
- The average of 5 samples is 24%.
- The average of at least one sample succeeding is 69%.

I suspect that the latter value is the success rate for ToT. However, it differs from the value (74%) reported in Table 2. 
I also recomputed the other json files (standard and chain-of-thought) and they resulted in exactly the same as those reported values in Table 2.

Is your method of evaluating the ToT's success rate different from other approaches, or did you upload a different file for it?

Thank you,
Jin

**Comment by ysymyth** [comment]
Hi @jin8 in game of 24, ToT will use a simple heuristic at the end of generation to choose one of the 5 samples (e.g., valid equation, uses all four numbers, right hand side is 24), so success rate is 69 not 24. there is variance across running, as explained in https://github.com/princeton-nlp/tree-of-thought-llm#paper-trajectories 

Will close for now but feel free to open new ones!
