### ISSUE TITLE
How to fine tune the small model on the tree of thoughts 

### ISSUE THREAD

**Issue by Jasheenshaik** [princeton-nlp/tree-of-thought-llm#57]
Hi @ysymyth  

Can you please guide me how can i finitune the opt-350m or any other low parameters models  on  custom datasets like @ https://huggingface.co/datasets/meta-math/MetaMathQA  which includes the task to plan the specific problem and generate the end answer.

Thanks 
Jasheen shaik

**Comment by ysymyth** [comment]
Hi, you probably need to fine-tune a generator and an evaluator. The former is easier, the latter you need some negative samples, e.g. https://github.com/openai/prm800k ?

**Comment by KylinSong** [comment]
Hi  @ysymyth 
I've been using ToT and came across the **evaluate** function in MiniCrosswordsTask. Did I miss where it's used, or is it intended for future purposes? 
Thanks!

**Comment by ysymyth** [comment]
it should be fully functional. is there any error you occur?

**Comment by ysymyth** [comment]
Close it for now, feel free to open new ones.
