### ISSUE TITLE
Bypassing Maximum 4097 Tokens.

### ISSUE THREAD

**Issue by milstrike** [princeton-nlp/tree-of-thought-llm#58]
Hi @ysymyth, can you help me bypass the "This model's maximum context length is 4097 tokens. However, your messages resulted in 4238 tokens. Please reduce the length of the messages." error? Because many times I tried for this parameter: 
n_generate_sample=5, 
n_evaluate_sample=1, 
n_select_sample=5

It always returns the error I mentioned above (both models, GPT4 and GPT-3.5-Turbo. Thank You.

To re-run your experiment on creative writing, what parameter should I use?

**Comment by ysymyth** [comment]
what's your error like? also, I think gpt-4 has 8192 tokens now?

**Comment by ysymyth** [comment]
Close it for now, feel free to open new ones.
