### ISSUE TITLE
propose_prompt and value_prompt independently use?

### ISSUE THREAD

**Issue by qq941134965** [princeton-nlp/tree-of-thought-llm#60]
Hi @ysymyth,

the prompts for game24 includes "propose_prompt" and "value_prompt", and I'm not sure if I should use these two prompts independently or if there is a certain order?

If possible, could you use the following example from game24 to illustrate the order in which to enter these two prompts "propose_prompt" and "value_prompt":
4 4 6 8

**Comment by ysymyth** [comment]
https://github.com/princeton-nlp/tree-of-thought-llm/blob/master/src/tot/methods/bfs.py
